services:
  database:
    image: postgres:15
    container_name: forwarder_backend_database
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: forwarder_backend_application
    ports:
      - "8080:8080"
    build:
      context: ForwarderBackend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
  sender:
    container_name: sender_api
    build:
      context: SenderApi
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./SenderApi/mounted:/mounted
volumes:
  postgres_data: