version: '3.8'

services:
  database:
    image: postgres:15
    container_name: forwarder_backend_database
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: forwarder_backend_application
    build:
      context: ForwarderBackend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
  sender:
    container_name: sender_api
    build:
      context: SenderApi
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - telegram_session:mounted
volumes:
  postgres_data:
  telegram_session: